import { Effect } from './type';
import { BLACK, WHITE, TRANSPARENT } from './constants';

const FONT_PRESETS: Effect[] = [
  {
    title: '无特效',
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    shadowColor: undefined,
    shadowBlur: undefined,
    stroke: undefined,
    strokeWidth: undefined,
    shadowOpacity: 0,
  },
  {
    title: '特效1',
    fill: '#FBDA00',
    shadowOffsetX: 3,
    shadowOffsetY: 3,
    shadowColor: BLACK,
    shadowBlur: 0,
    stroke: BLACK,
    strokeWidth: 1,
    shadowOpacity: 1,
  },
  {
    title: '特效2',
    fill: WHITE,
    shadowOffsetX: 0,
    shadowOffsetY: 4,
    shadowBlur: 0,
    shadowColor: BLACK,
    stroke: BLACK,
    strokeWidth: 1,
    shadowOpacity: 1,
  },
  {
    title: '特效3',
    fill: '#F80000  ',
    shadowOffsetX: 0,
    shadowOffsetY: 1,
    shadowBlur: 3,
    shadowColor: BLACK,
    stroke: BLACK,
    strokeWidth: 1,
    shadowOpacity: 1,
  },
  // {
  //   title: '特效4',
  //   fill: '#000  ',
  //   shadowOffsetX: 0,
  //   shadowOffsetY: 1,
  //   shadowBlur: 3,
  //   shadowColor: BLACK,
  //   shadowOpacity: 0.3,
  //   stroke: BLACK,
  //   strokeWidth: 1,
  // },
  // {
  //   title: '多重描边',
  //   strokeWidth: 2,
  //   stroke: '#fff',
  //   shadowOffsetX: 0,
  //   shadowOffsetY: 0,
  //   shadowColor: BLACK,
  //   shadowBlur: 0,
  // },
];

const IMAGE_PRESETS: Effect[] = [
  {
    title: '无特效',
    fill: TRANSPARENT,
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    shadowColor: undefined,
    shadowBlur: 0,
    stroke: BLACK,
    strokeWidth: 0,
    shadowOpacity: 0,
  },
  {
    title: '特效1 ',
    fill: TRANSPARENT,
    shadowOffsetX: 4,
    shadowOffsetY: 2,
    shadowColor: BLACK,
    shadowBlur: 4,
    stroke: BLACK,
    strokeWidth: 0,
    shadowOpacity: 0.4,
  },
  {
    title: '特效2 ',
    fill: TRANSPARENT,
    shadowOffsetX: 3,
    shadowOffsetY: -3,
    shadowColor: BLACK,
    shadowBlur: 4,
    stroke: BLACK,
    strokeWidth: 0,
    shadowOpacity: 0.4,
  },
  {
    title: '特效3 ',
    fill: TRANSPARENT,
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    shadowColor: BLACK,
    shadowBlur: 8,
    stroke: BLACK,
    strokeWidth: 0,
    shadowOpacity: 0.4,
  },
  // {
  //   title: '特效4（内描边）',
  //   shadowOffsetX: 0,
  //   shadowOffsetY: 0,
  //   shadowColor: BLACK,
  //   shadowBlur: 8,
  //   stroke: '#4BE2AC',
  //   strokeWidth: 1,
  //   shadowOpacity: 1,
  // },
  // {
  //   title: '特效5（外描边） ',
  //   shadowOffsetX: 0,
  //   shadowOffsetY: 0,
  //   shadowColor: BLACK,
  //   shadowBlur: 0,
  //   stroke: '#4BE2AC',
  //   strokeWidth: 1,
  //   shadowOpacity: 1,
  // },
];
export { FONT_PRESETS, IMAGE_PRESETS };
